import styles from "@/styles/Home.module.css";
import { Inter } from "@next/font/google";
import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import Balancer from "react-wrap-balancer";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        {/* <div className={styles.description}>
          <p>
            Get started by editing&nbsp;
            <code className={styles.code}>pages/index.js</code>
          </p>
          <div>
            <Link href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app">
              By{" "}
              <Image
                src="/vercel.svg"
                alt="Vercel Logo"
                className={styles.vercelLogo}
                width={100}
                height={24}
                priority
              />
            </Link>
          </div>
        </div> */}

        <div className={styles.stackWrapper}>
          <div className={styles.center}>
            <Image
              className={styles.logo}
              src="/next.svg"
              alt="Next.js Logo"
              width={180}
              height={37}
              priority
            />

            <div className={styles.thirteen}>
              <Image
                src="/thirteen.svg"
                alt="13"
                width={40}
                height={31}
                priority
              />
            </div>
          </div>
          <h1>+</h1>
          <div className={styles.center}>
            <Image
              className={styles.logo}
              src="/authjs-logo.webp"
              alt="Next.js Logo"
              width={100}
              height={100}
              priority
            />
            <h2>Auth.js</h2>
          </div>
        </div>

        <div className={styles.grid}>
          <Link href="/admin" className={styles.card}>
            <h2 className={inter.className}>
              <Balancer ratio={0.85}>
                Admin Dashboard <span>-&gt;</span>
              </Balancer>
            </h2>
            <p className={inter.className}>
              School admin can grant and deny access to teachers to write in the
              database.
            </p>
          </Link>

          <Link href="/author" className={styles.card}>
            <h2 className={inter.className}>
              <Balancer ratio={0.85}>
                Teacher Dashboard <span>-&gt;</span>
              </Balancer>
            </h2>
            <p className={inter.className}>
              Teachers can add student to the school database.
            </p>
          </Link>

          <Link href="/user" className={styles.card}>
            <h2 className={inter.className}>
              <Balancer ratio={0.85}>
                Student Dashboard <span>-&gt;</span>
              </Balancer>
            </h2>
            <p className={inter.className}>
              Students can only read/view their name on the school portal
            </p>
          </Link>
        </div>
      </main>
    </>
  );
}
